import Navbar from "./components/Navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export type TMetadata = {
  title: string;
  description: string;
  // image: string,
  // url: string,
  // date: string,
  // author: string,
  // keywords: string,
  // twitter: string,
  // facebook: string,
  // instagram: string,
  // youtube: string,
  // linkedin: string,
  // github: string,
  // email: string,
  // phone: string,
  // address: string,
  // city: string,
  // state: string,
  // zip: string,
  // country: string,
  // website: string,
  // twitterHandle: string,
  // facebookHandle: string,
  // instagramHandle: string,
  // youtubeHandle: string,
  // linkedinHandle: string,
  // githubHandle: string,
  // emailHandle: string,
  // phoneHandle: string,
  // addressHandle: string,
  // cityHandle: string,
  // stateHandle: string,
  // zipHandle: string,
  // countryHandle: string,
  // websiteHandle: string,
};
export const metadata: TMetadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="bg-gray-100 min-h-screen w-full">
          <main className="max-w-screen-2xl m-auto bg-white">
            <Navbar />
            {children}
          </main>
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
